### ISSUE TITLE
stroom_service_on_boot missing from config

### ISSUE THREAD

**Issue by arterialplan** [gchq/stroom-ansible#17]
stroom\roles\setup\systemd\tasks\main.yml requires stroom_service_on_boot to be set, this is not in the configuration currently.

I added "stroom_service_on_boot: true" to the group_vars/all file

**Comment by arterialplan** [comment]
This is for dw-v7 branch

**Comment by stroomdev00** [comment]
cf05d17b34748c792a998d99104108a9d0b34623
ea10553a7df13665fc709e62d487d9b054527802
9ca055c0cad3179cb4732f875bb3639bea131b38
