### ISSUE TITLE
docker setup incorrect for versions newer than v7.0-beta.139

### ISSUE THREAD

**Issue by arterialplan** [gchq/stroom-ansible#18]
In file "~/stroom_core_test/stroom_core_test-v7.0-beta.142/volumes/stroom/config/config.yml" I had to change the line 128 from:
    enableDistributedJobsOnBootstrap: ${STROOM_DISTRIBUTED_JOBS_ENABLED_ON_BOOTSTRAP:-true}
to
    enableJobsOnBootstrap: ${STROOM_DISTRIBUTED_JOBS_ENABLED_ON_BOOTSTRAP:-true}

the error leading me to this was:
 Caused by: io.dropwizard.configuration.ConfigurationParsingException: /stroom/config/config.yml has an error:
   * Unrecognized field at: appConfig.job.enableDistributedJobsOnBootstrap
     Did you mean?:
       - enableJobsOnBootstrap
       - executionInterval
       - enabled
       - db

I suspect this was updated in stroom v7.0-beta.139, but ansible wasn't updated to match.  It embedded in 
config/multi_node_mixed_cluster/example_inventory/files_and_templates/stroom/config/config.yml.j2
config/single_node_stroom_core_stack/example_inventory/files_and_templates/volumes/stroom/config/config.yml.j2

**Comment by arterialplan** [comment]
This is for dw-v7 branch

**Comment by stroomdev00** [comment]
Fixed in latest version.

**Comment by stroomdev00** [comment]
d1653947eb6375debb4c33b2c0a8aba636aa1b3d
