### ISSUE TITLE
multi_node_mixed_cluster inventory file is incorrect

### ISSUE THREAD

**Issue by burnalting** [gchq/stroom-ansible#3]
The example inventory for the multi_node_mixed_cluster incorrectly specifies to host groupings incorrectly.
`stroom-services-stack:` should be `stroom_services_stack:`
`stroom-database:` should be `stroom_database:`

**Comment by at055612** [comment]
Thanks.  Fixed in 3c63b110dd52b3fbc36093d1396d911d0e980145
