### ISSUE TITLE
Timeout for get_url tasks

### ISSUE THREAD

**Issue by burnalting** [gchq/stroom-ansible#4]
All **get_url** modules should specify a `timeout` parameter of say 120 seconds for non-AWS deployments (aka low speed networks) to prevent timeouts due to variable network bandwidth.

I.E. Add
`timeout: 120`
to all **get_url** modules

**Comment by at055612** [comment]
Fixed in 7c18e829e8629ae0c2f0855c50bcc91a48c85c68
