### ISSUE TITLE
If change Stroom version from 6.0.27-1 to 6.0.34, cannot change admin password

### ISSUE THREAD

**Issue by burnalting** [gchq/stroom-ansible#8]
If one runs a deployment based on 6.0.34. I.E. setting in (group_vars/all)

stroom_version: "v6.0.34"
and
stack_version: "{{ stroom_version }}"

One the deployment occurs, the first access to the UI cycles forever when one enters the admin password.

**Comment by burnalting** [comment]
This issue appears against other versions of Stroom post 6.0.27.

**Comment by at055612** [comment]
Is this a fresh install or installing on top of an older version?

**Comment by burnalting** [comment]
Fresh install.

**Comment by at055612** [comment]
what flavour of deployment is this, single node docker or mixed economy?

**Comment by burnalting** [comment]
Mixed economy, specifically `multi_node_mixed_cluster` from _stroom-ansible-master_

**Comment by at055612** [comment]
This appears to have been an issue with the setting of HOST_IP in the services stack env file.  Fixed in 5209ca0d2d60ae9a399333209d18cbc9515c0130.

Let me know if it is now working for you.
